(ql:quickload :local-time)
(local-time:enable-read-macros)

(defparameter *series* '(:SERIES-NAME "Pertussis standard series" :TARGET-DISEASE :PERTUSSIS
 :VACCINE-GROUP :DTA-P/TDAP/TD :SERIES-ADMIN-GUIDANCE NIL :SERIES-TYPE
 :STANDARD :EQUIVALENT-SERIES-GROUPS NIL :REQUIRED-GENDER NIL :SELECT-SERIES
 (:DEFAULT-SERIES T :PRODUCT-PATH NIL :SERIES-GROUP-NAME :STANDARD
  :SERIES-GROUP 1 :SERIES-PRIORITY :A :SERIES-PREFERENCE 1 :MIN-AGE-TO-START
  NIL :MAX-AGE-TO-START ((:AMOUNT 12 :UNIT :MONTH) (:AMOUNT -4 :UNIT :DAY)))
 :INDICATION
 ((:OBSERVATION-CODE NIL :DESCRIPTION NIL :BEGIN-AGE NIL :END-AGE NIL :GUIDANCE
   NIL))
 :SERIES-DOSE
 ((:DOSE-NUMBER :DOSE-1 :AGE
   ((:ABS-MIN-AGE ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :MIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK)) :EARLIEST-REC-AGE ((:AMOUNT 2 :UNIT :MONTH))
     :LATEST-REC-AGE ((:AMOUNT 3 :UNIT :MONTH) (:AMOUNT 4 :UNIT :WEEK))
     :MAX-AGE NIL :EFFECTIVE-DATE NIL :CESSATION-DATE NIL))
   :INTERVAL
   ((:FROM-PREVIOUS NIL :FROM-TARGET-DOSE NIL :FROM-MOST-RECENT NIL
     :FROM-RELEVANT-OBS NIL :ABS-MIN-INT NIL :MIN-INT NIL :EARLIEST-REC-INT NIL
     :LATEST-REC-INT NIL :INTERVAL-PRIORITY NIL :EFFECTIVE-DATE NIL
     :CESSATION-DATE NIL))
   :ALLOWABLE-INTERVAL
   ((:FROM-PREVIOUS NIL :FROM-TARGET-DOSE NIL :ABS-MIN-INT NIL :EFFECTIVE-DATE
     NIL :CESSATION-DATE NIL))
   :PREFERABLE-VACCINE
   ((:VACCINE-TYPE "DTaP" :CVX 20 :BEGIN-AGE ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE
     ((:AMOUNT 7 :UNIT :YEAR)) :TRADE-NAME NIL :MVX NIL :VOLUME 0.5
     :FORECAST-VACCINE-TYPE NIL)
    (:VACCINE-TYPE "DTaP, 5 pertussis antigens" :CVX 106 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE ((:AMOUNT 7 :UNIT :YEAR)) :TRADE-NAME
     NIL :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE NIL)
    (:VACCINE-TYPE "DTaP-HepB-IPV" :CVX 110 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE ((:AMOUNT 7 :UNIT :YEAR)) :TRADE-NAME
     NIL :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE NIL)
    (:VACCINE-TYPE "DTaP-Hib-IPV" :CVX 120 :BEGIN-AGE ((:AMOUNT 6 :UNIT :WEEK))
     :END-AGE ((:AMOUNT 5 :UNIT :YEAR)) :TRADE-NAME NIL :MVX NIL :VOLUME 0.5
     :FORECAST-VACCINE-TYPE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB" :CVX 146 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE ((:AMOUNT 5 :UNIT :YEAR)) :TRADE-NAME
     NIL :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE NIL))
   :ALLOWABLE-VACCINE
   ((:VACCINE-TYPE "DTP" :CVX 1 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP" :CVX 20 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib" :CVX 22 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib" :CVX 50 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib-HepB" :CVX 102 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, 5 pertussis antigens" :CVX 106 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, Unspecified Formulation" :CVX 107 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-HepB-IPV" :CVX 110 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib-IPV" :CVX 120 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV" :CVX 130 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB,historical" :CVX 132 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB" :CVX 146 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib" :CVX 170 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-hepB-Hib Pentavalent Non-US" :CVX 198 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL))
   :INADVERTENT-VACCINE ((:VACCINE-TYPE "Tdap" :CVX 115)) :CONDITIONAL-SKIP
   ((:CONTEXT :EVALUATION :SET-LOGIC :N/A :SET
     ((:SET-ID 1 :SET-DESCRIPTION
       "Dose is not required for those 7 years or older" :EFFECTIVE-DATE NIL
       :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :AGE :START-DATE NIL :END-DATE NIL
         :BEGIN-AGE ((:AMOUNT 7 :UNIT :YEAR)) :END-AGE NIL :INTERVAL NIL
         :DOSE-COUNT NIL :DOSE-TYPE NIL :DOSE-COUNT-LOGIC NIL :VACCINE-TYPES
         NIL :SERIES-GROUPS NIL)))))
    (:CONTEXT :FORECAST :SET-LOGIC :OR :SET
     ((:SET-ID 2 :SET-DESCRIPTION
       "Dose is not required for those 7 years or older" :EFFECTIVE-DATE NIL
       :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :AGE :START-DATE NIL :END-DATE NIL
         :BEGIN-AGE ((:AMOUNT 7 :UNIT :YEAR)) :END-AGE NIL :INTERVAL NIL
         :DOSE-COUNT NIL :DOSE-TYPE NIL :DOSE-COUNT-LOGIC NIL :VACCINE-TYPES
         NIL :SERIES-GROUPS NIL)))
      (:SET-ID 3 :SET-DESCRIPTION
       "Dose is not required if the patient has received 6 or more total doses to date"
       :EFFECTIVE-DATE NIL :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
         :END-DATE NIL :BEGIN-AGE
         ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL
         :INTERVAL NIL :DOSE-COUNT 5 :DOSE-TYPE :TOTAL :DOSE-COUNT-LOGIC
         :GREATER-THAN :VACCINE-TYPES
         (1 11 20 22 50 102 106 107 110 115 120 130 132 146 170) :SERIES-GROUPS
         NIL))))))
   :RECURRING-DOSE NIL :SEASONAL-RECOMMENDATION
   (:START-DATE NIL :END-DATE NIL))
  (:DOSE-NUMBER :DOSE-2 :AGE
   ((:ABS-MIN-AGE ((:AMOUNT 10 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :MIN-AGE
     ((:AMOUNT 10 :UNIT :WEEK)) :EARLIEST-REC-AGE ((:AMOUNT 4 :UNIT :MONTH))
     :LATEST-REC-AGE ((:AMOUNT 5 :UNIT :MONTH) (:AMOUNT 4 :UNIT :WEEK))
     :MAX-AGE NIL :EFFECTIVE-DATE NIL :CESSATION-DATE NIL))
   :INTERVAL
   ((:FROM-PREVIOUS T :FROM-TARGET-DOSE NIL :FROM-MOST-RECENT NIL
     :FROM-RELEVANT-OBS (:TEXT NIL :CODE NIL) :ABS-MIN-INT
     ((:AMOUNT 4 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :MIN-INT
     ((:AMOUNT 4 :UNIT :WEEK)) :EARLIEST-REC-INT ((:AMOUNT 8 :UNIT :WEEK))
     :LATEST-REC-INT ((:AMOUNT 13 :UNIT :WEEK)) :INTERVAL-PRIORITY NIL
     :EFFECTIVE-DATE NIL :CESSATION-DATE NIL))
   :ALLOWABLE-INTERVAL
   ((:FROM-PREVIOUS NIL :FROM-TARGET-DOSE NIL :ABS-MIN-INT NIL :EFFECTIVE-DATE
     NIL :CESSATION-DATE NIL))
   :PREFERABLE-VACCINE
   ((:VACCINE-TYPE "DTaP" :CVX 20 :BEGIN-AGE ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE
     ((:AMOUNT 7 :UNIT :YEAR)) :TRADE-NAME NIL :MVX NIL :VOLUME 0.5
     :FORECAST-VACCINE-TYPE NIL)
    (:VACCINE-TYPE "DTaP, 5 pertussis antigens" :CVX 106 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE ((:AMOUNT 7 :UNIT :YEAR)) :TRADE-NAME
     NIL :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE NIL)
    (:VACCINE-TYPE "DTaP-HepB-IPV" :CVX 110 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE ((:AMOUNT 7 :UNIT :YEAR)) :TRADE-NAME
     NIL :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE NIL)
    (:VACCINE-TYPE "DTaP-Hib-IPV" :CVX 120 :BEGIN-AGE ((:AMOUNT 6 :UNIT :WEEK))
     :END-AGE ((:AMOUNT 5 :UNIT :YEAR)) :TRADE-NAME NIL :MVX NIL :VOLUME 0.5
     :FORECAST-VACCINE-TYPE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB" :CVX 146 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE ((:AMOUNT 5 :UNIT :YEAR)) :TRADE-NAME
     NIL :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE NIL))
   :ALLOWABLE-VACCINE
   ((:VACCINE-TYPE "DTP" :CVX 1 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP" :CVX 20 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib" :CVX 22 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib" :CVX 50 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib-HepB" :CVX 102 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, 5 pertussis antigens" :CVX 106 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, Unspecified Formulation" :CVX 107 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-HepB-IPV" :CVX 110 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib-IPV" :CVX 120 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV" :CVX 130 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB,historical" :CVX 132 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB" :CVX 146 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib" :CVX 170 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-hepB-Hib Pentavalent Non-US" :CVX 198 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL))
   :INADVERTENT-VACCINE ((:VACCINE-TYPE "Tdap" :CVX 115)) :CONDITIONAL-SKIP
   ((:CONTEXT :EVALUATION :SET-LOGIC :N/A :SET
     ((:SET-ID 1 :SET-DESCRIPTION
       "Dose is not required for those 7 years or older" :EFFECTIVE-DATE NIL
       :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :AGE :START-DATE NIL :END-DATE NIL
         :BEGIN-AGE ((:AMOUNT 7 :UNIT :YEAR)) :END-AGE NIL :INTERVAL NIL
         :DOSE-COUNT NIL :DOSE-TYPE NIL :DOSE-COUNT-LOGIC NIL :VACCINE-TYPES
         NIL :SERIES-GROUPS NIL)))))
    (:CONTEXT :FORECAST :SET-LOGIC :OR :SET
     ((:SET-ID 2 :SET-DESCRIPTION
       "Dose is not required for those 7 years or older" :EFFECTIVE-DATE NIL
       :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :AGE :START-DATE NIL :END-DATE NIL
         :BEGIN-AGE ((:AMOUNT 7 :UNIT :YEAR)) :END-AGE NIL :INTERVAL NIL
         :DOSE-COUNT NIL :DOSE-TYPE NIL :DOSE-COUNT-LOGIC NIL :VACCINE-TYPES
         NIL :SERIES-GROUPS NIL)))
      (:SET-ID 3 :SET-DESCRIPTION
       "Dose is not required if the patient has received 6 or more total doses to date"
       :EFFECTIVE-DATE NIL :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
         :END-DATE NIL :BEGIN-AGE
         ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL
         :INTERVAL NIL :DOSE-COUNT 5 :DOSE-TYPE :TOTAL :DOSE-COUNT-LOGIC
         :GREATER-THAN :VACCINE-TYPES
         (1 11 20 22 50 102 106 107 110 115 120 130 132 146 170) :SERIES-GROUPS
         NIL))))))
   :RECURRING-DOSE NIL :SEASONAL-RECOMMENDATION
   (:START-DATE NIL :END-DATE NIL))
  (:DOSE-NUMBER :DOSE-3 :AGE
   ((:ABS-MIN-AGE ((:AMOUNT 14 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :MIN-AGE
     ((:AMOUNT 14 :UNIT :WEEK)) :EARLIEST-REC-AGE ((:AMOUNT 6 :UNIT :MONTH))
     :LATEST-REC-AGE ((:AMOUNT 7 :UNIT :MONTH) (:AMOUNT 4 :UNIT :WEEK))
     :MAX-AGE NIL :EFFECTIVE-DATE NIL :CESSATION-DATE NIL))
   :INTERVAL
   ((:FROM-PREVIOUS T :FROM-TARGET-DOSE NIL :FROM-MOST-RECENT NIL
     :FROM-RELEVANT-OBS (:TEXT NIL :CODE NIL) :ABS-MIN-INT
     ((:AMOUNT 4 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :MIN-INT
     ((:AMOUNT 4 :UNIT :WEEK)) :EARLIEST-REC-INT ((:AMOUNT 8 :UNIT :WEEK))
     :LATEST-REC-INT ((:AMOUNT 13 :UNIT :WEEK)) :INTERVAL-PRIORITY NIL
     :EFFECTIVE-DATE NIL :CESSATION-DATE NIL))
   :ALLOWABLE-INTERVAL
   ((:FROM-PREVIOUS NIL :FROM-TARGET-DOSE NIL :ABS-MIN-INT NIL :EFFECTIVE-DATE
     NIL :CESSATION-DATE NIL))
   :PREFERABLE-VACCINE
   ((:VACCINE-TYPE "DTaP" :CVX 20 :BEGIN-AGE ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE
     ((:AMOUNT 7 :UNIT :YEAR)) :TRADE-NAME NIL :MVX NIL :VOLUME 0.5
     :FORECAST-VACCINE-TYPE NIL)
    (:VACCINE-TYPE "DTaP, 5 pertussis antigens" :CVX 106 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE ((:AMOUNT 7 :UNIT :YEAR)) :TRADE-NAME
     NIL :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE NIL)
    (:VACCINE-TYPE "DTaP-HepB-IPV" :CVX 110 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE ((:AMOUNT 7 :UNIT :YEAR)) :TRADE-NAME
     NIL :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE NIL)
    (:VACCINE-TYPE "DTaP-Hib-IPV" :CVX 120 :BEGIN-AGE ((:AMOUNT 6 :UNIT :WEEK))
     :END-AGE ((:AMOUNT 5 :UNIT :YEAR)) :TRADE-NAME NIL :MVX NIL :VOLUME 0.5
     :FORECAST-VACCINE-TYPE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB" :CVX 146 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE ((:AMOUNT 5 :UNIT :YEAR)) :TRADE-NAME
     NIL :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE NIL))
   :ALLOWABLE-VACCINE
   ((:VACCINE-TYPE "DTP" :CVX 1 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP" :CVX 20 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib" :CVX 22 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib" :CVX 50 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib-HepB" :CVX 102 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, 5 pertussis antigens" :CVX 106 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, Unspecified Formulation" :CVX 107 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-HepB-IPV" :CVX 110 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib-IPV" :CVX 120 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV" :CVX 130 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB,historical" :CVX 132 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB" :CVX 146 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib" :CVX 170 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-hepB-Hib Pentavalent Non-US" :CVX 198 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL))
   :INADVERTENT-VACCINE ((:VACCINE-TYPE "Tdap" :CVX 115)) :CONDITIONAL-SKIP
   ((:CONTEXT :EVALUATION :SET-LOGIC :N/A :SET
     ((:SET-ID 1 :SET-DESCRIPTION
       "Dose is not required for those 7 years or older" :EFFECTIVE-DATE NIL
       :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :AGE :START-DATE NIL :END-DATE NIL
         :BEGIN-AGE ((:AMOUNT 7 :UNIT :YEAR)) :END-AGE NIL :INTERVAL NIL
         :DOSE-COUNT NIL :DOSE-TYPE NIL :DOSE-COUNT-LOGIC NIL :VACCINE-TYPES
         NIL :SERIES-GROUPS NIL)))))
    (:CONTEXT :FORECAST :SET-LOGIC :OR :SET
     ((:SET-ID 2 :SET-DESCRIPTION
       "Dose is not required for those 7 years or older" :EFFECTIVE-DATE NIL
       :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :AGE :START-DATE NIL :END-DATE NIL
         :BEGIN-AGE ((:AMOUNT 7 :UNIT :YEAR)) :END-AGE NIL :INTERVAL NIL
         :DOSE-COUNT NIL :DOSE-TYPE NIL :DOSE-COUNT-LOGIC NIL :VACCINE-TYPES
         NIL :SERIES-GROUPS NIL)))
      (:SET-ID 3 :SET-DESCRIPTION
       "Dose is not required if the patient has received 6 or more total doses to date"
       :EFFECTIVE-DATE NIL :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
         :END-DATE NIL :BEGIN-AGE
         ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL
         :INTERVAL NIL :DOSE-COUNT 5 :DOSE-TYPE :TOTAL :DOSE-COUNT-LOGIC
         :GREATER-THAN :VACCINE-TYPES
         (1 11 20 22 50 102 106 107 110 115 120 130 132 146 170) :SERIES-GROUPS
         NIL))))))
   :RECURRING-DOSE NIL :SEASONAL-RECOMMENDATION
   (:START-DATE NIL :END-DATE NIL))
  (:DOSE-NUMBER :DOSE-4 :AGE
   ((:ABS-MIN-AGE ((:AMOUNT 12 :UNIT :MONTH) (:AMOUNT -4 :UNIT :DAY)) :MIN-AGE
     ((:AMOUNT 15 :UNIT :MONTH)) :EARLIEST-REC-AGE ((:AMOUNT 15 :UNIT :MONTH))
     :LATEST-REC-AGE ((:AMOUNT 19 :UNIT :MONTH) (:AMOUNT 4 :UNIT :WEEK))
     :MAX-AGE NIL :EFFECTIVE-DATE NIL :CESSATION-DATE NIL))
   :INTERVAL
   ((:FROM-PREVIOUS T :FROM-TARGET-DOSE NIL :FROM-MOST-RECENT NIL
     :FROM-RELEVANT-OBS (:TEXT NIL :CODE NIL) :ABS-MIN-INT
     ((:AMOUNT 6 :UNIT :MONTH) (:AMOUNT -4 :UNIT :DAY)) :MIN-INT
     ((:AMOUNT 6 :UNIT :MONTH)) :EARLIEST-REC-INT ((:AMOUNT 6 :UNIT :MONTH))
     :LATEST-REC-INT ((:AMOUNT 13 :UNIT :MONTH) (:AMOUNT 4 :UNIT :WEEK))
     :INTERVAL-PRIORITY NIL :EFFECTIVE-DATE NIL :CESSATION-DATE NIL))
   :ALLOWABLE-INTERVAL
   ((:FROM-PREVIOUS T :FROM-TARGET-DOSE NIL :ABS-MIN-INT
     ((:AMOUNT 4 :UNIT :MONTH) (:AMOUNT -4 :UNIT :DAY)) :EFFECTIVE-DATE NIL
     :CESSATION-DATE NIL))
   :PREFERABLE-VACCINE
   ((:VACCINE-TYPE "DTaP" :CVX 20 :BEGIN-AGE ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE
     ((:AMOUNT 7 :UNIT :YEAR)) :TRADE-NAME NIL :MVX NIL :VOLUME 0.5
     :FORECAST-VACCINE-TYPE NIL)
    (:VACCINE-TYPE "DTaP, 5 pertussis antigens" :CVX 106 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE ((:AMOUNT 7 :UNIT :YEAR)) :TRADE-NAME
     NIL :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE NIL)
    (:VACCINE-TYPE "DTaP-Hib-IPV" :CVX 120 :BEGIN-AGE ((:AMOUNT 6 :UNIT :WEEK))
     :END-AGE ((:AMOUNT 5 :UNIT :YEAR)) :TRADE-NAME NIL :MVX NIL :VOLUME 0.5
     :FORECAST-VACCINE-TYPE NIL))
   :ALLOWABLE-VACCINE
   ((:VACCINE-TYPE "DTP" :CVX 1 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP" :CVX 20 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib" :CVX 22 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib" :CVX 50 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib-HepB" :CVX 102 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, 5 pertussis antigens" :CVX 106 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, Unspecified Formulation" :CVX 107 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-HepB-IPV" :CVX 110 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "Tdap" :CVX 115 :BEGIN-AGE
     ((:AMOUNT 12 :UNIT :MONTH) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib-IPV" :CVX 120 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV" :CVX 130 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB,historical" :CVX 132 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB" :CVX 146 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib" :CVX 170 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-hepB-Hib Pentavalent Non-US" :CVX 198 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL))
   :INADVERTENT-VACCINE ((:VACCINE-TYPE NIL :CVX NIL)) :CONDITIONAL-SKIP
   ((:CONTEXT :EVALUATION :SET-LOGIC :N/A :SET
     ((:SET-ID 1 :SET-DESCRIPTION
       "Dose is not required for those 4 years or older" :EFFECTIVE-DATE NIL
       :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :AGE :START-DATE NIL :END-DATE NIL
         :BEGIN-AGE ((:AMOUNT 4 :UNIT :YEAR) (:AMOUNT -4 :UNIT :DAY)) :END-AGE
         NIL :INTERVAL NIL :DOSE-COUNT NIL :DOSE-TYPE NIL :DOSE-COUNT-LOGIC NIL
         :VACCINE-TYPES NIL :SERIES-GROUPS NIL)))))
    (:CONTEXT :FORECAST :SET-LOGIC :OR :SET
     ((:SET-ID 2 :SET-DESCRIPTION
       "Dose is not required for those 4 years or older" :EFFECTIVE-DATE NIL
       :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :AGE :START-DATE NIL :END-DATE NIL
         :BEGIN-AGE ((:AMOUNT 4 :UNIT :YEAR)) :END-AGE NIL :INTERVAL NIL
         :DOSE-COUNT NIL :DOSE-TYPE NIL :DOSE-COUNT-LOGIC NIL :VACCINE-TYPES
         NIL :SERIES-GROUPS NIL)))
      (:SET-ID 3 :SET-DESCRIPTION
       "Dose is not required if the patient has received 6 or more total doses to date"
       :EFFECTIVE-DATE NIL :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
         :END-DATE NIL :BEGIN-AGE
         ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL
         :INTERVAL NIL :DOSE-COUNT 5 :DOSE-TYPE :TOTAL :DOSE-COUNT-LOGIC
         :GREATER-THAN :VACCINE-TYPES
         (1 11 20 22 50 102 106 107 110 115 120 130 132 146 170) :SERIES-GROUPS
         NIL))))))
   :RECURRING-DOSE NIL :SEASONAL-RECOMMENDATION
   (:START-DATE NIL :END-DATE NIL))
  (:DOSE-NUMBER :DOSE-5 :AGE
   ((:ABS-MIN-AGE ((:AMOUNT 4 :UNIT :YEAR) (:AMOUNT -4 :UNIT :DAY)) :MIN-AGE
     ((:AMOUNT 4 :UNIT :YEAR)) :EARLIEST-REC-AGE ((:AMOUNT 4 :UNIT :YEAR))
     :LATEST-REC-AGE ((:AMOUNT 7 :UNIT :YEAR)) :MAX-AGE NIL :EFFECTIVE-DATE NIL
     :CESSATION-DATE NIL))
   :INTERVAL
   ((:FROM-PREVIOUS T :FROM-TARGET-DOSE NIL :FROM-MOST-RECENT NIL
     :FROM-RELEVANT-OBS (:TEXT NIL :CODE NIL) :ABS-MIN-INT
     ((:AMOUNT 6 :UNIT :MONTH) (:AMOUNT -4 :UNIT :DAY)) :MIN-INT
     ((:AMOUNT 6 :UNIT :MONTH)) :EARLIEST-REC-INT ((:AMOUNT 3 :UNIT :YEAR))
     :LATEST-REC-INT ((:AMOUNT 4 :UNIT :YEAR) (:AMOUNT 4 :UNIT :WEEK))
     :INTERVAL-PRIORITY NIL :EFFECTIVE-DATE NIL :CESSATION-DATE NIL))
   :ALLOWABLE-INTERVAL
   ((:FROM-PREVIOUS NIL :FROM-TARGET-DOSE NIL :ABS-MIN-INT NIL :EFFECTIVE-DATE
     NIL :CESSATION-DATE NIL))
   :PREFERABLE-VACCINE
   ((:VACCINE-TYPE "DTaP" :CVX 20 :BEGIN-AGE ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE
     ((:AMOUNT 7 :UNIT :YEAR)) :TRADE-NAME NIL :MVX NIL :VOLUME 0.5
     :FORECAST-VACCINE-TYPE NIL)
    (:VACCINE-TYPE "DTaP, 5 pertussis antigens" :CVX 106 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE ((:AMOUNT 7 :UNIT :YEAR)) :TRADE-NAME
     NIL :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE NIL)
    (:VACCINE-TYPE "DTaP-IPV" :CVX 130 :BEGIN-AGE ((:AMOUNT 4 :UNIT :YEAR))
     :END-AGE ((:AMOUNT 7 :UNIT :YEAR)) :TRADE-NAME NIL :MVX NIL :VOLUME 0.5
     :FORECAST-VACCINE-TYPE NIL))
   :ALLOWABLE-VACCINE
   ((:VACCINE-TYPE "DTP" :CVX 1 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP" :CVX 20 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib" :CVX 22 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib" :CVX 50 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib-HepB" :CVX 102 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, 5 pertussis antigens" :CVX 106 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, Unspecified Formulation" :CVX 107 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-HepB-IPV" :CVX 110 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "Tdap" :CVX 115 :BEGIN-AGE
     ((:AMOUNT 12 :UNIT :MONTH) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib-IPV" :CVX 120 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV" :CVX 130 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB,historical" :CVX 132 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB" :CVX 146 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib" :CVX 170 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-hepB-Hib Pentavalent Non-US" :CVX 198 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL))
   :INADVERTENT-VACCINE ((:VACCINE-TYPE NIL :CVX NIL)) :CONDITIONAL-SKIP
   ((:CONTEXT :EVALUATION :SET-LOGIC :N/A :SET
     ((:SET-ID 1 :SET-DESCRIPTION
       "Dose is not required for those 7 years or older" :EFFECTIVE-DATE NIL
       :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :AGE :START-DATE NIL :END-DATE NIL
         :BEGIN-AGE ((:AMOUNT 7 :UNIT :YEAR)) :END-AGE NIL :INTERVAL NIL
         :DOSE-COUNT NIL :DOSE-TYPE NIL :DOSE-COUNT-LOGIC NIL :VACCINE-TYPES
         NIL :SERIES-GROUPS NIL)))))
    (:CONTEXT :FORECAST :SET-LOGIC :OR :SET
     ((:SET-ID 2 :SET-DESCRIPTION
       "Dose is not required for those 7 years or older" :EFFECTIVE-DATE NIL
       :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :AGE :START-DATE NIL :END-DATE NIL
         :BEGIN-AGE ((:AMOUNT 7 :UNIT :YEAR)) :END-AGE NIL :INTERVAL NIL
         :DOSE-COUNT NIL :DOSE-TYPE NIL :DOSE-COUNT-LOGIC NIL :VACCINE-TYPES
         NIL :SERIES-GROUPS NIL)))
      (:SET-ID 3 :SET-DESCRIPTION
       "Dose is not required if the patient has received 6 or more total doses to date"
       :EFFECTIVE-DATE NIL :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
         :END-DATE NIL :BEGIN-AGE
         ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL
         :INTERVAL NIL :DOSE-COUNT 5 :DOSE-TYPE :TOTAL :DOSE-COUNT-LOGIC
         :GREATER-THAN :VACCINE-TYPES
         (1 11 20 22 50 102 106 107 110 115 120 130 132 146 170) :SERIES-GROUPS
         NIL))))))
   :RECURRING-DOSE NIL :SEASONAL-RECOMMENDATION
   (:START-DATE NIL :END-DATE NIL))
  (:DOSE-NUMBER :DOSE-6 :AGE
   ((:ABS-MIN-AGE ((:AMOUNT 7 :UNIT :YEAR)) :MIN-AGE ((:AMOUNT 7 :UNIT :YEAR))
     :EARLIEST-REC-AGE ((:AMOUNT 7 :UNIT :YEAR)) :LATEST-REC-AGE
     ((:AMOUNT 7 :UNIT :YEAR)) :MAX-AGE NIL :EFFECTIVE-DATE NIL :CESSATION-DATE
     NIL))
   :INTERVAL
   ((:FROM-PREVIOUS T :FROM-TARGET-DOSE NIL :FROM-MOST-RECENT NIL
     :FROM-RELEVANT-OBS (:TEXT NIL :CODE NIL) :ABS-MIN-INT
     ((:AMOUNT 0 :UNIT :DAY)) :MIN-INT ((:AMOUNT 0 :UNIT :DAY))
     :EARLIEST-REC-INT ((:AMOUNT 0 :UNIT :DAY)) :LATEST-REC-INT NIL
     :INTERVAL-PRIORITY "override" :EFFECTIVE-DATE NIL :CESSATION-DATE NIL))
   :ALLOWABLE-INTERVAL
   ((:FROM-PREVIOUS NIL :FROM-TARGET-DOSE NIL :ABS-MIN-INT NIL :EFFECTIVE-DATE
     NIL :CESSATION-DATE NIL))
   :PREFERABLE-VACCINE
   ((:VACCINE-TYPE "Tdap" :CVX 115 :BEGIN-AGE ((:AMOUNT 7 :UNIT :YEAR))
     :END-AGE NIL :TRADE-NAME NIL :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE
     NIL))
   :ALLOWABLE-VACCINE
   ((:VACCINE-TYPE "DTP" :CVX 1 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP" :CVX 20 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib" :CVX 22 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib" :CVX 50 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib-HepB" :CVX 102 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, 5 pertussis antigens" :CVX 106 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, Unspecified Formulation" :CVX 107 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-HepB-IPV" :CVX 110 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "Tdap" :CVX 115 :BEGIN-AGE
     ((:AMOUNT 12 :UNIT :MONTH) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib-IPV" :CVX 120 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV" :CVX 130 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB,historical" :CVX 132 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB" :CVX 146 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib" :CVX 170 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-hepB-Hib Pentavalent Non-US" :CVX 198 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL))
   :INADVERTENT-VACCINE ((:VACCINE-TYPE NIL :CVX NIL)) :CONDITIONAL-SKIP
   ((:CONTEXT :BOTH :SET-LOGIC :OR :SET
     ((:SET-ID 1 :SET-DESCRIPTION
       "Dose is not required if the patient has received 2 doses"
       :EFFECTIVE-DATE NIL :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
         :END-DATE NIL :BEGIN-AGE NIL :END-AGE NIL :INTERVAL NIL :DOSE-COUNT 2
         :DOSE-TYPE :VALID :DOSE-COUNT-LOGIC :EQUAL-TO :VACCINE-TYPES NIL
         :SERIES-GROUPS NIL)))
      (:SET-ID 2 :SET-DESCRIPTION
       "Dose is not required if the patient has received 3 doses"
       :EFFECTIVE-DATE NIL :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
         :END-DATE NIL :BEGIN-AGE NIL :END-AGE NIL :INTERVAL NIL :DOSE-COUNT 3
         :DOSE-TYPE :VALID :DOSE-COUNT-LOGIC :EQUAL-TO :VACCINE-TYPES NIL
         :SERIES-GROUPS NIL)))
      (:SET-ID 3 :SET-DESCRIPTION
       "Dose is not required if the patient has received 4 doses with 1 pertussis- containing vaccine on or after 4 years"
       :EFFECTIVE-DATE NIL :CESSATION-DATE NIL :CONDITION-LOGIC "AND"
       :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
         :END-DATE NIL :BEGIN-AGE NIL :END-AGE NIL :INTERVAL NIL :DOSE-COUNT 4
         :DOSE-TYPE :VALID :DOSE-COUNT-LOGIC :EQUAL-TO :VACCINE-TYPES NIL
         :SERIES-GROUPS NIL)
        (:CONDITION-ID 2 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
         :END-DATE NIL :BEGIN-AGE
         ((:AMOUNT 4 :UNIT :YEAR) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL
         :INTERVAL NIL :DOSE-COUNT 0 :DOSE-TYPE :VALID :DOSE-COUNT-LOGIC
         :GREATER-THAN :VACCINE-TYPES
         (1 20 22 50 102 106 107 110 115 120 130 132 146 170) :SERIES-GROUPS
         NIL)))
      (:SET-ID 4 :SET-DESCRIPTION
       "Dose is not required if the patient has received more than 4 doses"
       :EFFECTIVE-DATE NIL :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
         :END-DATE NIL :BEGIN-AGE NIL :END-AGE NIL :INTERVAL NIL :DOSE-COUNT 4
         :DOSE-TYPE :VALID :DOSE-COUNT-LOGIC :GREATER-THAN :VACCINE-TYPES NIL
         :SERIES-GROUPS NIL))))))
   :RECURRING-DOSE NIL :SEASONAL-RECOMMENDATION
   (:START-DATE NIL :END-DATE NIL))
  (:DOSE-NUMBER :DOSE-7 :AGE
   ((:ABS-MIN-AGE ((:AMOUNT 7 :UNIT :YEAR)) :MIN-AGE ((:AMOUNT 7 :UNIT :YEAR))
     :EARLIEST-REC-AGE ((:AMOUNT 7 :UNIT :YEAR)) :LATEST-REC-AGE
     ((:AMOUNT 7 :UNIT :YEAR)) :MAX-AGE NIL :EFFECTIVE-DATE NIL :CESSATION-DATE
     NIL))
   :INTERVAL
   ((:FROM-PREVIOUS T :FROM-TARGET-DOSE NIL :FROM-MOST-RECENT NIL
     :FROM-RELEVANT-OBS (:TEXT NIL :CODE NIL) :ABS-MIN-INT
     ((:AMOUNT 4 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :MIN-INT
     ((:AMOUNT 4 :UNIT :WEEK)) :EARLIEST-REC-INT ((:AMOUNT 4 :UNIT :WEEK))
     :LATEST-REC-INT NIL :INTERVAL-PRIORITY "override" :EFFECTIVE-DATE NIL
     :CESSATION-DATE NIL))
   :ALLOWABLE-INTERVAL
   ((:FROM-PREVIOUS NIL :FROM-TARGET-DOSE NIL :ABS-MIN-INT NIL :EFFECTIVE-DATE
     NIL :CESSATION-DATE NIL))
   :PREFERABLE-VACCINE
   ((:VACCINE-TYPE "Tdap" :CVX 115 :BEGIN-AGE ((:AMOUNT 7 :UNIT :YEAR))
     :END-AGE NIL :TRADE-NAME NIL :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE
     NIL))
   :ALLOWABLE-VACCINE
   ((:VACCINE-TYPE "DTP" :CVX 1 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP" :CVX 20 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib" :CVX 22 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib" :CVX 50 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib-HepB" :CVX 102 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, 5 pertussis antigens" :CVX 106 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, Unspecified Formulation" :CVX 107 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-HepB-IPV" :CVX 110 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "Tdap" :CVX 115 :BEGIN-AGE
     ((:AMOUNT 12 :UNIT :MONTH) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib-IPV" :CVX 120 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV" :CVX 130 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB,historical" :CVX 132 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB" :CVX 146 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib" :CVX 170 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-hepB-Hib Pentavalent Non-US" :CVX 198 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL))
   :INADVERTENT-VACCINE ((:VACCINE-TYPE NIL :CVX NIL)) :CONDITIONAL-SKIP
   ((:CONTEXT :BOTH :SET-LOGIC :OR :SET
     ((:SET-ID 1 :SET-DESCRIPTION
       "Dose is not required if the patient has received more than 2 doses."
       :EFFECTIVE-DATE NIL :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
         :END-DATE NIL :BEGIN-AGE NIL :END-AGE NIL :INTERVAL NIL :DOSE-COUNT 2
         :DOSE-TYPE :VALID :DOSE-COUNT-LOGIC :GREATER-THAN :VACCINE-TYPES NIL
         :SERIES-GROUPS NIL)))
      (:SET-ID 2 :SET-DESCRIPTION
       "Dose is not required if the patient has received 1 valid dose on or after 7 years."
       :EFFECTIVE-DATE NIL :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
         :END-DATE NIL :BEGIN-AGE ((:AMOUNT 7 :UNIT :YEAR)) :END-AGE NIL
         :INTERVAL NIL :DOSE-COUNT 0 :DOSE-TYPE :VALID :DOSE-COUNT-LOGIC
         :GREATER-THAN :VACCINE-TYPES NIL :SERIES-GROUPS NIL))))))
   :RECURRING-DOSE NIL :SEASONAL-RECOMMENDATION
   (:START-DATE NIL :END-DATE NIL))
  (:DOSE-NUMBER :DOSE-8 :AGE
   ((:ABS-MIN-AGE ((:AMOUNT 7 :UNIT :YEAR)) :MIN-AGE ((:AMOUNT 7 :UNIT :YEAR))
     :EARLIEST-REC-AGE ((:AMOUNT 7 :UNIT :YEAR)) :LATEST-REC-AGE
     ((:AMOUNT 7 :UNIT :YEAR)) :MAX-AGE NIL :EFFECTIVE-DATE NIL :CESSATION-DATE
     NIL))
   :INTERVAL
   ((:FROM-PREVIOUS T :FROM-TARGET-DOSE NIL :FROM-MOST-RECENT NIL
     :FROM-RELEVANT-OBS (:TEXT NIL :CODE NIL) :ABS-MIN-INT
     ((:AMOUNT 6 :UNIT :MONTH) (:AMOUNT -4 :UNIT :DAY)) :MIN-INT
     ((:AMOUNT 6 :UNIT :MONTH)) :EARLIEST-REC-INT ((:AMOUNT 6 :UNIT :MONTH))
     :LATEST-REC-INT NIL :INTERVAL-PRIORITY "override" :EFFECTIVE-DATE NIL
     :CESSATION-DATE NIL))
   :ALLOWABLE-INTERVAL
   ((:FROM-PREVIOUS NIL :FROM-TARGET-DOSE NIL :ABS-MIN-INT NIL :EFFECTIVE-DATE
     NIL :CESSATION-DATE NIL))
   :PREFERABLE-VACCINE
   ((:VACCINE-TYPE "Tdap" :CVX 115 :BEGIN-AGE ((:AMOUNT 7 :UNIT :YEAR))
     :END-AGE NIL :TRADE-NAME NIL :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE
     NIL))
   :ALLOWABLE-VACCINE
   ((:VACCINE-TYPE "DTP" :CVX 1 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP" :CVX 20 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib" :CVX 22 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib" :CVX 50 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib-HepB" :CVX 102 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, 5 pertussis antigens" :CVX 106 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, Unspecified Formulation" :CVX 107 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-HepB-IPV" :CVX 110 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "Tdap" :CVX 115 :BEGIN-AGE
     ((:AMOUNT 12 :UNIT :MONTH) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib-IPV" :CVX 120 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV" :CVX 130 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB,historical" :CVX 132 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB" :CVX 146 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib" :CVX 170 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-hepB-Hib Pentavalent Non-US" :CVX 198 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL))
   :INADVERTENT-VACCINE ((:VACCINE-TYPE NIL :CVX NIL)) :CONDITIONAL-SKIP
   ((:CONTEXT :BOTH :SET-LOGIC :OR :SET
     ((:SET-ID 1 :SET-DESCRIPTION
       "Dose is not required if the patient has received more than 3 doses"
       :EFFECTIVE-DATE NIL :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
         :END-DATE NIL :BEGIN-AGE NIL :END-AGE NIL :INTERVAL NIL :DOSE-COUNT 3
         :DOSE-TYPE :VALID :DOSE-COUNT-LOGIC :GREATER-THAN :VACCINE-TYPES NIL
         :SERIES-GROUPS NIL)))
      (:SET-ID 2 :SET-DESCRIPTION
       "Dose is not required if the patient has received 1 valid dose on or after 7 years."
       :EFFECTIVE-DATE NIL :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
         :END-DATE NIL :BEGIN-AGE ((:AMOUNT 7 :UNIT :YEAR)) :END-AGE NIL
         :INTERVAL NIL :DOSE-COUNT 0 :DOSE-TYPE :VALID :DOSE-COUNT-LOGIC
         :GREATER-THAN :VACCINE-TYPES NIL :SERIES-GROUPS NIL))))))
   :RECURRING-DOSE NIL :SEASONAL-RECOMMENDATION
   (:START-DATE NIL :END-DATE NIL))
  (:DOSE-NUMBER :DOSE-9 :AGE
   ((:ABS-MIN-AGE ((:AMOUNT 10 :UNIT :YEAR)) :MIN-AGE
     ((:AMOUNT 11 :UNIT :YEAR)) :EARLIEST-REC-AGE ((:AMOUNT 11 :UNIT :YEAR))
     :LATEST-REC-AGE ((:AMOUNT 13 :UNIT :YEAR) (:AMOUNT 4 :UNIT :WEEK))
     :MAX-AGE NIL :EFFECTIVE-DATE NIL :CESSATION-DATE NIL))
   :INTERVAL
   ((:FROM-PREVIOUS NIL :FROM-TARGET-DOSE NIL :FROM-MOST-RECENT
     "09;28;35;113;138;139" :FROM-RELEVANT-OBS (:TEXT NIL :CODE NIL)
     :ABS-MIN-INT ((:AMOUNT 6 :UNIT :MONTH) (:AMOUNT -4 :UNIT :DAY)) :MIN-INT
     ((:AMOUNT 6 :UNIT :MONTH)) :EARLIEST-REC-INT ((:AMOUNT 6 :UNIT :MONTH))
     :LATEST-REC-INT NIL :INTERVAL-PRIORITY NIL :EFFECTIVE-DATE NIL
     :CESSATION-DATE NIL))
   :ALLOWABLE-INTERVAL
   ((:FROM-PREVIOUS NIL :FROM-TARGET-DOSE NIL :ABS-MIN-INT NIL :EFFECTIVE-DATE
     NIL :CESSATION-DATE NIL))
   :PREFERABLE-VACCINE
   ((:VACCINE-TYPE "Tdap" :CVX 115 :BEGIN-AGE ((:AMOUNT 7 :UNIT :YEAR))
     :END-AGE NIL :TRADE-NAME NIL :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE
     NIL))
   :ALLOWABLE-VACCINE
   ((:VACCINE-TYPE "DTP" :CVX 1 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP" :CVX 20 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib" :CVX 22 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib" :CVX 50 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib-HepB" :CVX 102 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, 5 pertussis antigens" :CVX 106 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, Unspecified Formulation" :CVX 107 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-HepB-IPV" :CVX 110 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "Tdap" :CVX 115 :BEGIN-AGE
     ((:AMOUNT 12 :UNIT :MONTH) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib-IPV" :CVX 120 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV" :CVX 130 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB,historical" :CVX 132 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB" :CVX 146 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib" :CVX 170 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-hepB-Hib Pentavalent Non-US" :CVX 198 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL))
   :INADVERTENT-VACCINE ((:VACCINE-TYPE NIL :CVX NIL)) :CONDITIONAL-SKIP
   ((:CONTEXT :BOTH :SET-LOGIC :OR :SET
     ((:SET-ID 1 :SET-DESCRIPTION
       "Dose is not required if the patient has received more than 3 doses"
       :EFFECTIVE-DATE NIL :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
         :END-DATE NIL :BEGIN-AGE NIL :END-AGE NIL :INTERVAL NIL :DOSE-COUNT 3
         :DOSE-TYPE :VALID :DOSE-COUNT-LOGIC :GREATER-THAN :VACCINE-TYPES NIL
         :SERIES-GROUPS NIL)))
      (:SET-ID 2 :SET-DESCRIPTION
       "Dose is not required if the patient has received 1 valid dose on or after 10 years."
       :EFFECTIVE-DATE NIL :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
         :END-DATE NIL :BEGIN-AGE ((:AMOUNT 10 :UNIT :YEAR)) :END-AGE NIL
         :INTERVAL NIL :DOSE-COUNT 0 :DOSE-TYPE :VALID :DOSE-COUNT-LOGIC
         :GREATER-THAN :VACCINE-TYPES NIL :SERIES-GROUPS NIL))))))
   :RECURRING-DOSE NIL :SEASONAL-RECOMMENDATION
   (:START-DATE NIL :END-DATE NIL))
  (:DOSE-NUMBER :DOSE-10 :AGE
   ((:ABS-MIN-AGE ((:AMOUNT 10 :UNIT :YEAR)) :MIN-AGE
     ((:AMOUNT 11 :UNIT :YEAR)) :EARLIEST-REC-AGE ((:AMOUNT 11 :UNIT :YEAR))
     :LATEST-REC-AGE ((:AMOUNT 13 :UNIT :YEAR) (:AMOUNT 4 :UNIT :WEEK))
     :MAX-AGE NIL :EFFECTIVE-DATE NIL :CESSATION-DATE NIL))
   :INTERVAL
   ((:FROM-PREVIOUS NIL :FROM-TARGET-DOSE NIL :FROM-MOST-RECENT
     "09;28;35;113;138;139" :FROM-RELEVANT-OBS (:TEXT NIL :CODE NIL)
     :ABS-MIN-INT ((:AMOUNT 0 :UNIT :DAY)) :MIN-INT ((:AMOUNT 0 :UNIT :DAY))
     :EARLIEST-REC-INT NIL :LATEST-REC-INT NIL :INTERVAL-PRIORITY "override"
     :EFFECTIVE-DATE NIL :CESSATION-DATE NIL))
   :ALLOWABLE-INTERVAL
   ((:FROM-PREVIOUS NIL :FROM-TARGET-DOSE NIL :ABS-MIN-INT NIL :EFFECTIVE-DATE
     NIL :CESSATION-DATE NIL))
   :PREFERABLE-VACCINE
   ((:VACCINE-TYPE "Tdap" :CVX 115 :BEGIN-AGE ((:AMOUNT 7 :UNIT :YEAR))
     :END-AGE NIL :TRADE-NAME NIL :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE
     NIL))
   :ALLOWABLE-VACCINE
   ((:VACCINE-TYPE "DTP" :CVX 1 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP" :CVX 20 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib" :CVX 22 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib" :CVX 50 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-Hib-HepB" :CVX 102 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, 5 pertussis antigens" :CVX 106 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP, Unspecified Formulation" :CVX 107 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-HepB-IPV" :CVX 110 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "Tdap" :CVX 115 :BEGIN-AGE
     ((:AMOUNT 12 :UNIT :MONTH) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-Hib-IPV" :CVX 120 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV" :CVX 130 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB,historical" :CVX 132 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib-HepB" :CVX 146 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTaP-IPV-Hib" :CVX 170 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
    (:VACCINE-TYPE "DTP-hepB-Hib Pentavalent Non-US" :CVX 198 :BEGIN-AGE
     ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL))
   :INADVERTENT-VACCINE ((:VACCINE-TYPE NIL :CVX NIL)) :CONDITIONAL-SKIP
   ((:CONTEXT :BOTH :SET-LOGIC :N/A :SET
     ((:SET-ID 1 :SET-DESCRIPTION
       "Dose is not required if the patient has received 1 or more doses after the age of 10 years"
       :EFFECTIVE-DATE NIL :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
       ((:CONDITION-ID 1 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
         :END-DATE NIL :BEGIN-AGE ((:AMOUNT 10 :UNIT :YEAR)) :END-AGE NIL
         :INTERVAL NIL :DOSE-COUNT 0 :DOSE-TYPE :VALID :DOSE-COUNT-LOGIC
         :GREATER-THAN :VACCINE-TYPES NIL :SERIES-GROUPS NIL))))))
   :RECURRING-DOSE NIL :SEASONAL-RECOMMENDATION
   (:START-DATE NIL :END-DATE NIL)))))
   
   (defparameter *medical* '(:ASSESSMENT-DATE @2020-08-13T00:00:00.000000Z :DOB
 @2013-08-26T00:00:00.000000Z :GENDER :FEMALE :MED-HISTORY-CODE NIL
 :MED-HISTORY-CODE-SYS NIL :MED-HISTORY-TEXT NIL :OBSERVATION-CODES NIL :DOSES
 ((:CVX 110 :MVX :SKB :VACCINE-NAME "PEDIARIX" :DATE-ADMINISTERED
   @2016-06-23T00:00:00.000000Z :LOT-EXPIRATION NIL :CONDITION NIL)
  (:CVX 110 :MVX :SKB :VACCINE-NAME "PEDIARIX" :DATE-ADMINISTERED
   @2017-09-27T00:00:00.000000Z :LOT-EXPIRATION NIL :CONDITION NIL)
  (:CVX 110 :MVX :SKB :VACCINE-NAME "PEDIARIX" :DATE-ADMINISTERED
   @2020-08-13T00:00:00.000000Z :LOT-EXPIRATION NIL :CONDITION NIL))))
   
   (defparameter *dose* '(:DOSE-NUMBER :DOSE-1 :AGE
 ((:ABS-MIN-AGE ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :MIN-AGE
   ((:AMOUNT 6 :UNIT :WEEK)) :EARLIEST-REC-AGE ((:AMOUNT 2 :UNIT :MONTH))
   :LATEST-REC-AGE ((:AMOUNT 3 :UNIT :MONTH) (:AMOUNT 4 :UNIT :WEEK)) :MAX-AGE
   NIL :EFFECTIVE-DATE NIL :CESSATION-DATE NIL))
 :INTERVAL
 ((:FROM-PREVIOUS NIL :FROM-TARGET-DOSE NIL :FROM-MOST-RECENT NIL
   :FROM-RELEVANT-OBS NIL :ABS-MIN-INT NIL :MIN-INT NIL :EARLIEST-REC-INT NIL
   :LATEST-REC-INT NIL :INTERVAL-PRIORITY NIL :EFFECTIVE-DATE NIL
   :CESSATION-DATE NIL))
 :ALLOWABLE-INTERVAL
 ((:FROM-PREVIOUS NIL :FROM-TARGET-DOSE NIL :ABS-MIN-INT NIL :EFFECTIVE-DATE
   NIL :CESSATION-DATE NIL))
 :PREFERABLE-VACCINE
 ((:VACCINE-TYPE "DTaP" :CVX 20 :BEGIN-AGE ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE
   ((:AMOUNT 7 :UNIT :YEAR)) :TRADE-NAME NIL :MVX NIL :VOLUME 0.5
   :FORECAST-VACCINE-TYPE NIL)
  (:VACCINE-TYPE "DTaP, 5 pertussis antigens" :CVX 106 :BEGIN-AGE
   ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE ((:AMOUNT 7 :UNIT :YEAR)) :TRADE-NAME NIL
   :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE NIL)
  (:VACCINE-TYPE "DTaP-HepB-IPV" :CVX 110 :BEGIN-AGE ((:AMOUNT 6 :UNIT :WEEK))
   :END-AGE ((:AMOUNT 7 :UNIT :YEAR)) :TRADE-NAME NIL :MVX NIL :VOLUME 0.5
   :FORECAST-VACCINE-TYPE NIL)
  (:VACCINE-TYPE "DTaP-Hib-IPV" :CVX 120 :BEGIN-AGE ((:AMOUNT 6 :UNIT :WEEK))
   :END-AGE ((:AMOUNT 5 :UNIT :YEAR)) :TRADE-NAME NIL :MVX NIL :VOLUME 0.5
   :FORECAST-VACCINE-TYPE NIL)
  (:VACCINE-TYPE "DTaP-IPV-Hib-HepB" :CVX 146 :BEGIN-AGE
   ((:AMOUNT 6 :UNIT :WEEK)) :END-AGE ((:AMOUNT 5 :UNIT :YEAR)) :TRADE-NAME NIL
   :MVX NIL :VOLUME 0.5 :FORECAST-VACCINE-TYPE NIL))
 :ALLOWABLE-VACCINE
 ((:VACCINE-TYPE "DTP" :CVX 1 :BEGIN-AGE
   ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
  (:VACCINE-TYPE "DTaP" :CVX 20 :BEGIN-AGE
   ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
  (:VACCINE-TYPE "DTP-Hib" :CVX 22 :BEGIN-AGE
   ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
  (:VACCINE-TYPE "DTaP-Hib" :CVX 50 :BEGIN-AGE
   ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
  (:VACCINE-TYPE "DTP-Hib-HepB" :CVX 102 :BEGIN-AGE
   ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
  (:VACCINE-TYPE "DTaP, 5 pertussis antigens" :CVX 106 :BEGIN-AGE
   ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
  (:VACCINE-TYPE "DTaP, Unspecified Formulation" :CVX 107 :BEGIN-AGE
   ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
  (:VACCINE-TYPE "DTaP-HepB-IPV" :CVX 110 :BEGIN-AGE
   ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
  (:VACCINE-TYPE "DTaP-Hib-IPV" :CVX 120 :BEGIN-AGE
   ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
  (:VACCINE-TYPE "DTaP-IPV" :CVX 130 :BEGIN-AGE
   ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
  (:VACCINE-TYPE "DTaP-IPV-Hib-HepB,historical" :CVX 132 :BEGIN-AGE
   ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
  (:VACCINE-TYPE "DTaP-IPV-Hib-HepB" :CVX 146 :BEGIN-AGE
   ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
  (:VACCINE-TYPE "DTaP-IPV-Hib" :CVX 170 :BEGIN-AGE
   ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL)
  (:VACCINE-TYPE "DTP-hepB-Hib Pentavalent Non-US" :CVX 198 :BEGIN-AGE
   ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL))
 :INADVERTENT-VACCINE ((:VACCINE-TYPE "Tdap" :CVX 115)) :CONDITIONAL-SKIP
 ((:CONTEXT :EVALUATION :SET-LOGIC :N/A :SET
   ((:SET-ID 1 :SET-DESCRIPTION
     "Dose is not required for those 7 years or older" :EFFECTIVE-DATE NIL
     :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
     ((:CONDITION-ID 1 :CONDITION-TYPE :AGE :START-DATE NIL :END-DATE NIL
       :BEGIN-AGE ((:AMOUNT 7 :UNIT :YEAR)) :END-AGE NIL :INTERVAL NIL
       :DOSE-COUNT NIL :DOSE-TYPE NIL :DOSE-COUNT-LOGIC NIL :VACCINE-TYPES NIL
       :SERIES-GROUPS NIL)))))
  (:CONTEXT :FORECAST :SET-LOGIC :OR :SET
   ((:SET-ID 2 :SET-DESCRIPTION
     "Dose is not required for those 7 years or older" :EFFECTIVE-DATE NIL
     :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
     ((:CONDITION-ID 1 :CONDITION-TYPE :AGE :START-DATE NIL :END-DATE NIL
       :BEGIN-AGE ((:AMOUNT 7 :UNIT :YEAR)) :END-AGE NIL :INTERVAL NIL
       :DOSE-COUNT NIL :DOSE-TYPE NIL :DOSE-COUNT-LOGIC NIL :VACCINE-TYPES NIL
       :SERIES-GROUPS NIL)))
    (:SET-ID 3 :SET-DESCRIPTION
     "Dose is not required if the patient has received 6 or more total doses to date"
     :EFFECTIVE-DATE NIL :CESSATION-DATE NIL :CONDITION-LOGIC NIL :CONDITION
     ((:CONDITION-ID 1 :CONDITION-TYPE :VACCINE-COUNT-BY-AGE :START-DATE NIL
       :END-DATE NIL :BEGIN-AGE
       ((:AMOUNT 6 :UNIT :WEEK) (:AMOUNT -4 :UNIT :DAY)) :END-AGE NIL :INTERVAL
       NIL :DOSE-COUNT 5 :DOSE-TYPE :TOTAL :DOSE-COUNT-LOGIC :GREATER-THAN
       :VACCINE-TYPES (1 11 20 22 50 102 106 107 110 115 120 130 132 146 170)
       :SERIES-GROUPS NIL))))))
 :RECURRING-DOSE NIL :SEASONAL-RECOMMENDATION (:START-DATE NIL :END-DATE NIL)))
 
 (defparameter *condition* '(:CONDITION-ID 1 :CONDITION-TYPE :AGE :START-DATE NIL :END-DATE NIL :BEGIN-AGE
 ((:AMOUNT 7 :UNIT :YEAR)) :END-AGE NIL :INTERVAL NIL :DOSE-COUNT NIL
 :DOSE-TYPE NIL :DOSE-COUNT-LOGIC NIL :VACCINE-TYPES NIL :SERIES-GROUPS NIL))
 
